services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=logistics-packages
  localstack:
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - localstack
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/logistics-packages
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password