services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-logistics-packages}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-logistics-packages}"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-password}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      # Database connection
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-logistics-packages}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-user}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-password}
      
      # RabbitMQ connection
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER:-user}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-password}

      # AWS (Localstack) connection
      - SPRING_CLOUD_AWS_SQS_ENDPOINT=http://localstack:4566
      - SPRING_CLOUD_AWS_S3_ENDPOINT=http://localstack:4566
      - SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY=test
      - SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY=test
      - SPRING_CLOUD_AWS_REGION_STATIC=us-east-1

      #Google Maps
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
volumes:
  postgres-data:
