flyway.url=jdbc:postgresql://localhost:5432/logistics-packages
flyway.user=user
flyway.password=password
flyway.locations=filesystem:C:\Users\csehuanes\Downloads\20261LogisticsPackages\Backend\src\main\resources\db\migration