spring:
  application:
    name: logistics-packages

  flyway:
    enabled: true

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
      s3:
        endpoint: http://localhost:4566

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  server:
    port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
      flyway:
        enabled: true