spring.application.name=logistics-packages

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/logistics-packages
spring.datasource.username=user
spring.datasource.password=password

# Flyway
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

# AWS
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test-access-key
spring.cloud.aws.credentials.secret-key=test-secret-key
spring.cloud.aws.endpoint=http://localhost:4566

# RabbitMQ Configuration (MOD1-IP-003)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Messaging Configuration
app.messaging.ruta.request.exchange=solicitudes_ruta_exchange
app.messaging.ruta.request.queue=solicitudes_ruta_queue
app.messaging.ruta.request.routing-key=solicitud.nueva
app.messaging.ruta.response.queue=respuestas_ruta_queue
app.messaging.ruta.dlx.exchange=solicitudes_ruta_dlx
app.messaging.ruta.dlx.queue=solicitudes_ruta_dlq

# PostMan
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.flyway.enabled=true
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always
