spring:
  application:
    name: logistics-packages

  flyway:
    enabled: true

  cloud:
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
      s3:
        endpoint: http://localhost:4566

aws:
  s3:
    bucket-name: logistics-packages-local
    auto-create-bucket: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: unimagt3ch@gmail.com    # CAMBIAR: tu correo de Gmail
    password: kpuq cbce lunr utaq        # CAMBIAR: contraseña de aplicación (NO tu contraseña de Google)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  server:
    port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
      flyway:
        enabled: true
