spring:
  cloud:
    aws:
      region:
        static: us-east-2

app:
  sqs:
    eventos-paquete-queue: arn:aws:sqs:us-east-2:383941187903:logistics-eventos-paquete
aws:
  sqs:
    ruta-response-queue: arn:aws:sqs:us-east-2:383941187903:respuestas-ruta-queue