spring:
  jpa:
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  cloud:
    flyway:
      baseline-on-migrate: true
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

# Queue names for M1-M2 SQS communication
aws:
  s3:
    bucket-name: logistics-packages
  sqs:
    ruta-request-queue: solicitudes-ruta-queue
    ruta-response-queue: respuestas-ruta-queue

app:
  sqs:
    eventos-paquete-queue: logistics-eventos-paquete
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  geocoding:
    api-key: AIzaSyAprQ3JrOi-3R7g3YErN0xApWs694RLSNA
    timeout-ms: 5000
  coverage:
    latitud-min: 4.0
    latitud-max: 12.0
    longitud-min: -77.0
    longitud-max: -72.0
  sede:
    latitud: 4.624335
    longitud: -74.063644
  jwt:
    secret: ${JWT_SECRET:dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbiBpbiBsb2dpc3RpY3MgcGFja2FnZXMgYXBpIDIwMjY=}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  tarifas:
    base: 5000
    por-kg: 250
    por-km: 150
    recargo-fragil: 1000
    recargo-peligroso: 2000
    recargo-carga-especial: 500
