spring.application.name=logistics-packages

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/logistics-packages
spring.datasource.username=user
spring.datasource.password=password

# Flyway
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

# AWS
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test-access-key
spring.cloud.aws.credentials.secret-key=test-secret-key
spring.cloud.aws.endpoint=http://localhost:4566

# PostMan
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.flyway.enabled=true
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always